// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9erEe_qTtEyQqFK4zdvcDivSsG8sC1I',
    appId: '1:349491312970:web:2a6d956509e983fcdaa9b3',
    messagingSenderId: '349491312970',
    projectId: 'flutter-modul-5',
    authDomain: 'flutter-modul-5.firebaseapp.com',
    storageBucket: 'flutter-modul-5.firebasestorage.app',
    measurementId: 'G-KJ3WVLNS1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67Oz86B-VcMcytfhiWAf9qV7hfcLr1ow',
    appId: '1:349491312970:android:68ed5c556183282fdaa9b3',
    messagingSenderId: '349491312970',
    projectId: 'flutter-modul-5',
    storageBucket: 'flutter-modul-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpO-6LHRYvD_yRi3S5sxo1ZJwRupPH3yg',
    appId: '1:349491312970:ios:fbceb6db82066a40daa9b3',
    messagingSenderId: '349491312970',
    projectId: 'flutter-modul-5',
    storageBucket: 'flutter-modul-5.firebasestorage.app',
    iosBundleId: 'com.example.trialFirebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpO-6LHRYvD_yRi3S5sxo1ZJwRupPH3yg',
    appId: '1:349491312970:ios:fbceb6db82066a40daa9b3',
    messagingSenderId: '349491312970',
    projectId: 'flutter-modul-5',
    storageBucket: 'flutter-modul-5.firebasestorage.app',
    iosBundleId: 'com.example.trialFirebaseCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE9erEe_qTtEyQqFK4zdvcDivSsG8sC1I',
    appId: '1:349491312970:web:cd8b2d7cb64db5f3daa9b3',
    messagingSenderId: '349491312970',
    projectId: 'flutter-modul-5',
    authDomain: 'flutter-modul-5.firebaseapp.com',
    storageBucket: 'flutter-modul-5.firebasestorage.app',
    measurementId: 'G-H00LERC2D5',
  );
}
